spring.application.name=novelscrapper
spring.datasource.url=jdbc:postgresql://localhost:5432/novel
spring.datasource.username=store
spring.datasource.password=store

# Recomiendo que Hibernate NO toque el schema
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true